import { useEffect, useState, useCallback } from "react";
import { useLiveRefresh } from "../components/LiveEvents";

const API = import.meta.env.VITE_API_URL ?? "http://localhost:8080";

async function apiFetch(path: string, token: string) {
  const r = await fetch(`${API}${path}`, { headers: { Authorization: `Bearer ${token}` } });
  return r.ok ? r.json() : null;
}

interface Incident {
  id: string;
  severity: string;
  message: string;
  serviceName: string;
  status: string;
  createdAt: string;
  resolvedAt?: string;
}

interface HealingEvent {
  id: string;
  targetLabel: string;
  action: string;
  reason: string;
  detectedAt: string;
  resolvedAt?: string;
}

interface ScalingEvent {
  id: string;
  targetLabel: string;
  action: string;
  previousReplicas: number;
  newReplicas?: number;
  targetReplicas?: number;
  at: string;
  reason?: string;
}

const SEV_COLOR: Record<string, string> = {
  CRITICAL: "#f43f5e", HIGH: "#fb923c", MEDIUM: "#f59e0b", LOW: "#22d3a0",
};

function timeAgo(iso: string | null): string {
  if (!iso) return "—";
  const s = Math.floor((Date.now() - new Date(iso).getTime()) / 1000);
  if (s < 60) return `${s}s ago`;
  if (s < 3600) return `${Math.floor(s / 60)}m ago`;
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
  return `${Math.floor(s / 86400)}d ago`;
}

function duration(start: string, end?: string): string {
  if (!end) return "ongoing";
  const s = Math.floor((new Date(end).getTime() - new Date(start).getTime()) / 1000);
  if (s < 60) return `${s}s`;
  if (s < 3600) return `${Math.floor(s / 60)}m ${s % 60}s`;
  return `${Math.floor(s / 3600)}h ${Math.floor((s % 3600) / 60)}m`;
}

function generateMarkdown(
  incident: Incident,
  healing: HealingEvent[],
  scaling: ScalingEvent[],
  rootCause: string,
  impact: string,
  resolution: string,
  actionItems: string,
): string {
  const now = new Date().toISOString().slice(0, 16).replace("T", " ");
  const related = healing.filter(h =>
    h.targetLabel?.toLowerCase().includes(incident.serviceName?.toLowerCase() ?? "")
  ).slice(0, 5);
  const relatedScaling = scaling.filter(s =>
    s.targetLabel?.toLowerCase().includes(incident.serviceName?.toLowerCase() ?? "")
  ).slice(0, 5);

  return `# Post-Mortem: ${incident.serviceName ?? "Unknown Service"}
**Severity:** ${incident.severity}
**Status:** ${incident.status}
**Duration:** ${duration(incident.createdAt, incident.resolvedAt)}
**Generated:** ${now} UTC

---

## Summary
${incident.message ?? "Alert fired for " + incident.serviceName}

## Impact
${impact || "_Describe customer/business impact here_"}

## Timeline
| Time | Event |
|------|-------|
| ${new Date(incident.createdAt).toISOString().slice(11, 19)} | 🚨 Alert fired: ${incident.severity} on \`${incident.serviceName}\` |
${related.map(h => `| ${new Date(h.detectedAt).toISOString().slice(11, 19)} | 🔧 Auto-healing triggered: ${h.action} (${h.reason}) |`).join("\n")}
${relatedScaling.map(s => `| ${new Date(s.at).toISOString().slice(11, 19)} | ⚖️ Scaling event: ${s.action} ${s.previousReplicas}→${s.newReplicas ?? s.targetReplicas} replicas |`).join("\n")}
${incident.resolvedAt ? `| ${new Date(incident.resolvedAt).toISOString().slice(11, 19)} | ✅ Incident resolved |` : "| — | 🔴 Incident still open |"}

## Root Cause
${rootCause || "_Describe the root cause identified_"}

## Resolution
${resolution || "_Describe what was done to resolve the incident_"}

## Action Items
${actionItems || "- [ ] Add more detailed monitoring\n- [ ] Review alerting thresholds\n- [ ] Update runbook"}

## Lessons Learned
- Review auto-healing coverage for \`${incident.serviceName}\`
- Consider adding canary deployment checks
- Ensure SLO budget burn rate alerts are configured

---
*Generated by AegisCloud Post-Mortem Generator*
`;
}

export function PostMortemPage({ token }: { token: string }) {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [healing, setHealing] = useState<HealingEvent[]>([]);
  const [scaling, setScaling] = useState<ScalingEvent[]>([]);
  const [selected, setSelected] = useState<Incident | null>(null);
  const [loading, setLoading] = useState(true);

  // Form fields
  const [rootCause, setRootCause] = useState("");
  const [impact, setImpact] = useState("");
  const [resolution, setResolution] = useState("");
  const [actionItems, setActionItems] = useState("- [ ] Add more detailed monitoring\n- [ ] Review alerting thresholds");
  const [preview, setPreview] = useState(false);
  const [copied, setCopied] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    const [alertData, healData, scaleData] = await Promise.all([
      apiFetch("/api/v1/alerts", token),
      apiFetch("/api/v1/control-plane/healing-events", token),
      apiFetch("/api/v1/control-plane/scaling-events", token),
    ]);
    const a: Incident[] = Array.isArray(alertData) ? alertData : (alertData?.alerts ?? []);
    setIncidents(a);
    setHealing(Array.isArray(healData) ? healData : (healData?.events ?? []));
    setScaling(Array.isArray(scaleData) ? scaleData : []);
    if (a.length > 0 && !selected) setSelected(a[0]);
    setLoading(false);
  }, [token]);

  useEffect(() => { load(); }, [load]);
  useLiveRefresh(["alert", "healing", "live-sync"], load);

  const markdown = selected
    ? generateMarkdown(selected, healing, scaling, rootCause, impact, resolution, actionItems)
    : "";

  const download = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `postmortem-${selected?.serviceName ?? "incident"}-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copy = () => {
    navigator.clipboard.writeText(markdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      {/* Header */}
      <div className="page-head">
        <h1>📝 Post-Mortem Generator</h1>
        <p>Select an incident, fill in the details, and generate a structured post-mortem report.</p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "300px 1fr", gap: 20, alignItems: "start" }}>
        {/* Incident list */}
        <div style={{ background: "#0d1117", border: "1px solid #1a2332", borderRadius: 12, overflow: "hidden" }}>
          <div style={{ padding: "12px 16px", borderBottom: "1px solid #1a2332", fontSize: 11, fontWeight: 700, color: "#60a5fa", textTransform: "uppercase", letterSpacing: 1 }}>
            Select Incident
          </div>
          {loading ? (
            <div style={{ padding: 24, textAlign: "center", color: "#4d5d72", fontSize: 13 }}>Loading…</div>
          ) : incidents.length === 0 ? (
            <div style={{ padding: 24, color: "#4d5d72", fontSize: 13 }}>No incidents found.</div>
          ) : (
            incidents.map((inc) => (
              <button
                key={inc.id}
                onClick={() => { setSelected(inc); setRootCause(""); setImpact(""); setResolution(""); setPreview(false); }}
                style={{
                  width: "100%", textAlign: "left", padding: "12px 16px",
                  border: "none", borderBottom: "1px solid #0d1117",
                  background: selected?.id === inc.id ? "#0f2a4a" : "transparent",
                  cursor: "pointer", transition: "background 0.15s",
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                  <span style={{
                    fontSize: 10, fontWeight: 700, padding: "1px 6px", borderRadius: 10,
                    background: (SEV_COLOR[inc.severity] ?? "#4d5d72") + "20",
                    color: SEV_COLOR[inc.severity] ?? "#4d5d72",
                    border: `1px solid ${(SEV_COLOR[inc.severity] ?? "#4d5d72")}40`,
                  }}>{inc.severity}</span>
                  <span style={{ fontSize: 10, color: inc.status === "RESOLVED" ? "#22d3a0" : "#f43f5e" }}>● {inc.status}</span>
                </div>
                <div style={{ fontSize: 13, fontWeight: 600, color: selected?.id === inc.id ? "#60a5fa" : "#e2e8f0" }}>{inc.serviceName}</div>
                <div style={{ fontSize: 11, color: "#4d5d72", marginTop: 2 }}>{timeAgo(inc.createdAt)}</div>
              </button>
            ))
          )}
        </div>

        {/* Editor */}
        {selected ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {/* Incident summary card */}
            <div style={{
              background: "#0a1628", border: `1px solid ${SEV_COLOR[selected.severity] ?? "#1a2332"}50`,
              borderRadius: 12, padding: "16px 20px",
              borderLeft: `4px solid ${SEV_COLOR[selected.severity] ?? "#3b82f6"}`,
            }}>
              <div style={{ fontSize: 11, color: "#4d5d72", marginBottom: 6 }}>INCIDENT</div>
              <div style={{ fontSize: 18, fontWeight: 700, color: "#e2e8f0" }}>{selected.serviceName}</div>
              <div style={{ fontSize: 13, color: "#94a3b8", marginTop: 4 }}>{selected.message}</div>
              <div style={{ display: "flex", gap: 16, marginTop: 10, fontSize: 12, color: "#4d5d72" }}>
                <span>🕐 {timeAgo(selected.createdAt)}</span>
                <span>⏱ Duration: {duration(selected.createdAt, selected.resolvedAt)}</span>
                <span>📊 {selected.severity}</span>
              </div>
            </div>

            {/* Form fields */}
            {[
              { label: "💥 Root Cause", value: rootCause, setter: setRootCause, placeholder: "Describe what caused the incident..." },
              { label: "📉 Business Impact", value: impact, setter: setImpact, placeholder: "Describe affected users/systems and business impact..." },
              { label: "✅ Resolution", value: resolution, setter: setResolution, placeholder: "Describe the steps taken to resolve the incident..." },
            ].map(({ label, value, setter, placeholder }) => (
              <div key={label}>
                <label style={{ fontSize: 12, fontWeight: 700, color: "#94a3b8", display: "block", marginBottom: 6 }}>{label}</label>
                <textarea
                  value={value}
                  onChange={e => setter(e.target.value)}
                  placeholder={placeholder}
                  rows={3}
                  style={{
                    width: "100%", background: "#0d1117", border: "1px solid #1a2332",
                    borderRadius: 8, padding: "10px 12px", color: "#e2e8f0",
                    fontSize: 13, resize: "vertical", outline: "none", boxSizing: "border-box",
                    transition: "border-color 0.15s", lineHeight: 1.6,
                  }}
                  onFocus={e => { e.target.style.borderColor = "#3b82f6"; }}
                  onBlur={e => { e.target.style.borderColor = "#1a2332"; }}
                />
              </div>
            ))}

            <div>
              <label style={{ fontSize: 12, fontWeight: 700, color: "#94a3b8", display: "block", marginBottom: 6 }}>📋 Action Items</label>
              <textarea
                value={actionItems}
                onChange={e => setActionItems(e.target.value)}
                rows={4}
                style={{
                  width: "100%", background: "#0d1117", border: "1px solid #1a2332",
                  borderRadius: 8, padding: "10px 12px", color: "#e2e8f0",
                  fontSize: 13, fontFamily: "monospace", resize: "vertical", outline: "none",
                  boxSizing: "border-box", transition: "border-color 0.15s",
                }}
                onFocus={e => { e.target.style.borderColor = "#3b82f6"; }}
                onBlur={e => { e.target.style.borderColor = "#1a2332"; }}
              />
            </div>

            {/* Actions */}
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button
                onClick={() => setPreview(p => !p)}
                style={{
                  padding: "9px 18px", background: preview ? "#1e3a5f" : "#141b25",
                  border: `1px solid ${preview ? "#3b82f6" : "#1a2332"}`,
                  borderRadius: 8, color: preview ? "#93c5fd" : "#94a3b8",
                  cursor: "pointer", fontSize: 13, fontWeight: 600, transition: "all 0.15s",
                }}
              >
                {preview ? "✏️ Edit" : "👁 Preview"}
              </button>
              <button
                onClick={copy}
                style={{
                  padding: "9px 18px", background: copied ? "#0a1f17" : "#141b25",
                  border: `1px solid ${copied ? "#22d3a0" : "#1a2332"}`,
                  borderRadius: 8, color: copied ? "#22d3a0" : "#94a3b8",
                  cursor: "pointer", fontSize: 13, fontWeight: 600, transition: "all 0.15s",
                }}
              >
                {copied ? "✅ Copied!" : "📋 Copy Markdown"}
              </button>
              <button
                onClick={download}
                style={{
                  padding: "9px 18px", background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
                  border: "none", borderRadius: 8, color: "#fff",
                  cursor: "pointer", fontSize: 13, fontWeight: 700,
                  boxShadow: "0 4px 14px #6366f140", transition: "all 0.15s",
                }}
              >
                ⬇️ Download .md
              </button>
            </div>

            {/* Preview / Raw */}
            <div style={{
              background: "#0a0e17", border: "1px solid #1a2332",
              borderRadius: 12, padding: "20px 24px", fontFamily: preview ? "inherit" : "monospace",
              fontSize: preview ? 14 : 12, color: "#94a3b8", lineHeight: 1.7,
              maxHeight: 460, overflowY: "auto",
              whiteSpace: preview ? "normal" : "pre-wrap",
            }}>
              {preview ? (
                <div dangerouslySetInnerHTML={{
                  __html: markdown
                    .replace(/^# (.+)$/m, '<h2 style="color:#e2e8f0;margin:0 0 12px">$1</h2>')
                    .replace(/^## (.+)$/gm, '<h3 style="color:#60a5fa;margin:16px 0 8px">$1</h3>')
                    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#e2e8f0">$1</strong>')
                    .replace(/`(.+?)`/g, '<code style="background:#1e293b;padding:1px 5px;border-radius:3px;font-size:11px">$1</code>')
                    .replace(/^- \[ \] (.+)$/gm, '<div style="display:flex;gap:6px;margin:3px 0"><span style="color:#4d5d72">☐</span><span>$1</span></div>')
                    .replace(/^---$/gm, '<hr style="border-color:#1a2332;margin:16px 0">')
                    .replace(/\n/g, '<br>')
                }} />
              ) : markdown}
            </div>
          </div>
        ) : (
          <div style={{ textAlign: "center", padding: "60px 40px", color: "#4d5d72" }}>
            <div style={{ fontSize: 48, marginBottom: 16 }}>📝</div>
            <div style={{ fontSize: 15, color: "#475569" }}>Select an incident to generate a post-mortem report</div>
          </div>
        )}
      </div>
    </div>
  );
}
